name: adyen_flutter
description: An Adyen Flutter plugin for tha API integration
version: 0.0.1
author: Alexandre Roba
homepage: https://github.com/lab-box/adyen_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.pikaway.adyen_flutter
    pluginClass: AdyenFlutterPlugin
